### ISSUE TITLE
empty-sequence() can not be promoted to parameter type object() of function components:facts()

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore#870] opened 2015-03-27 11:29 UTC
https://secxbrl.28.io/v1/_queries/public/api/facttable-for-component.jq?_method=POST&networkIdentifier=http:%2F%2Fwww.thecocacolacompany.com%2Frole%2FCondensedConsolidatedStatementsOfIncome&labels=true&format=json&token=c3049752-4d35-43da-82a2-f89f1b06f7a4&ticker=ko&fiscalYear=2014&fiscalPeriod=FY

![image](https://cloud.githubusercontent.com/assets/1012324/6866885/d05734e4-d47c-11e4-8b5c-c5d419db0305.png)

**Comment by gislenius** [comment] 2015-03-30 13:34
The component doesn't exist:
https://secxbrl-dev5.28.io/v1/_queries/public/api/components.jq?_method=POST&networkIdentifier=http:%2F%2Fwww.thecocacolacompany.com%2Frole%2FCondensedConsolidatedStatementsOfIncome&labels=true&format=json&token=foobar&ticker=ko&fiscalYear=2014&fiscalPeriod=FY
So that's a duplicate of
https://github.com/28msec/cellstore/issues/755
because the error message is wrong.

**Closed** 2015-04-16 15:48 UTC
Labels: duplicate
